# Generated by Django 2.1.7 on 2019-04-11 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orar', '0002_auto_20190409_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rand',
            name='titlu_curs',
        ),
        migrations.AddField(
            model_name='rand',
            name='curs',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='orar.Materie'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='cabinet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orar.Sala'),
        ),
    ]
