# Generated by Django 2.1.2 on 2019-04-17 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('url', models.TextField()),
                ('path', models.TextField()),
            ],
            options={
                'db_table': 'resources',
            },
        ),
    ]
