# Generated by Django 2.1.2 on 2019-04-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('MATERII', 'MATERII'), ('PROFESORI', 'PROFESORI'), ('SECRETARIAT', 'SECRETARIAT')], max_length=32)),
                ('body', models.TextField(blank=True, null=True)),
                ('inserted_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'news',
            },
        ),
    ]
