# Generated by Django 2.1.7 on 2019-04-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='published_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
