# Generated by Django 2.1.7 on 2019-04-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiiuser',
            name='tip_studii',
        ),
        migrations.AlterField(
            model_name='fiiuser',
            name='an_studiu',
            field=models.CharField(choices=[('-', '-'), ('I', 'I'), ('II', 'II'), ('III', 'III')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fiiuser',
            name='grupa',
            field=models.CharField(choices=[('-', '-'), ('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('A6', 'A6'), ('A7', 'A7'), ('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3'), ('B4', 'B4'), ('B5', 'B5'), ('B6', 'B6'), ('B7', 'B7'), ('X1', 'X1'), ('X2', 'X2'), ('X3', 'X3'), ('alta grupa', 'alta grupa')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fiiuser',
            name='rol',
            field=models.CharField(choices=[('-', '-'), ('Profesor', 'Profesor'), ('Student', 'Student'), ('Masterand', 'Masterand'), ('Doctorand', 'Doctorand')], max_length=20),
        ),
    ]
