# Generated by Django 2.1.7 on 2019-04-14 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personaliseApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaliseapp',
            old_name='board_id',
            new_name='board',
        ),
        migrations.RenameField(
            model_name='personaliseapp',
            old_name='student_id',
            new_name='student',
        ),
    ]
