# Generated by Django 2.1.7 on 2019-04-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curs', models.CharField(max_length=100)),
                ('zi', models.CharField(max_length=15)),
                ('ora_inceput', models.TimeField(auto_now_add=True)),
                ('ora_sfarsit', models.TimeField(auto_now_add=True)),
                ('an', models.IntegerField(blank=True, default=None, null=True)),
                ('grupa', models.CharField(max_length=5)),
                ('tip', models.CharField(max_length=20)),
                ('sala', models.CharField(max_length=20)),
                ('profesor', models.CharField(max_length=60)),
                ('pachet', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
    ]
