# Generated by Django 2.1.7 on 2019-04-15 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu_curs', models.CharField(max_length=51)),
                ('credite', models.IntegerField()),
                ('an', models.IntegerField()),
                ('semestru', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=31)),
                ('prenume', models.CharField(max_length=51)),
                ('grad_didactic', models.CharField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='Rand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zi', models.CharField(max_length=15)),
                ('ora_inceput', models.TimeField(auto_now_add=True)),
                ('ora_sfarsit', models.TimeField(auto_now_add=True)),
                ('grupa', models.CharField(max_length=5)),
                ('tip', models.CharField(max_length=20)),
                ('curs', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_query_name='cursul', to='orar.Materie')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orar.Profesor')),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_sala', models.CharField(max_length=15)),
                ('etaj', models.IntegerField()),
                ('echipari', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='rand',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orar.Sala'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='cabinet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orar.Sala'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='materii',
            field=models.ManyToManyField(to='orar.Materie'),
        ),
    ]
