# Generated by Django 2.1.7 on 2019-04-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='cabinet',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='materii',
        ),
        migrations.AddField(
            model_name='rand',
            name='an',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='rand',
            name='pachet',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='rand',
            name='curs',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rand',
            name='profesor',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='rand',
            name='sala',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Materie',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
        migrations.DeleteModel(
            name='Sala',
        ),
    ]
